import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from "../components/Footer"
import { Header } from '../components/Header'
import React from "react";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/about.js</code>
          </p>
          <Header />
        </div>
        <div className={styles.center}>
          <h1> About Page </h1>
        </div>
        <Footer />
      </main>
    </React.Fragment>
  )
}
