import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from "../components/Header"
import { Center } from "../components/Center"
import { Footer } from "../components/Footer"

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header page="index"/>
        <Center page="index"/>
        <Footer />
      </main>
    </>
  )
}
